### ISSUE TITLE
"Licence" should be renamed to "License"

### ISSUE THREAD

**Issue by MichaelWehar** [codeofdusk/marys#1]
I think that the file named "licence" at the top level of the repo should be renamed to "license".  Thank you!

**Comment by codeofdusk** [comment]
"licence" (with a c) is the noun form, "license" (with an s) is the verb form. The file contains the program's licence. I would accept a PR to rename the file to `COPYING` though!

Closing as wontfix.

**Comment by MichaelWehar** [comment]
Oh, I didn't realize that outside of the US License is spelled Licence when in noun form.  In the US, we just write license for both noun and verb form.  See here: https://www.grammarly.com/blog/licence-license/

**Comment by MichaelWehar** [comment]
As a result, I agree that closing this issue is a reasonable action to take.  Thank you!
